#!/bin/bash

# Copyright (c) 2022 Alexander Williams <alexwilliams@protonmail.ch>
# SPDX-License-Identifier: LicenseRef-MIT-Alex

# this script sets environment variables, and can be run either
# inside or outside the container

if [ -z "$PROJECT_NAME" ]; then
	PROJECT_NAME=$(realpath $0 | rev | cut -d/ -f 4 | rev)
fi
if [ -z "$PROJECT_DIR" ]; then
	PROJECT_DIR=$(dirname $(dirname $(dirname $(realpath $0))))
fi
if [ -z "$PROJECT_SHELL" ]; then
	PROJECT_SHELL=bash
fi
if [ -z "$PROJECT_DIR_LOCAL_OR_REMOTE" ]; then
	PROJECT_DIR_LOCAL_OR_REMOTE=$PROJECT_DIR
fi
if [ -z "$CONTAINER_DIR" ]; then
	CONTAINER_DIR=$PROJECT_DIR/container
fi
if [ -z "$SCRIPT_DIR" ]; then
	SCRIPT_DIR=$(dirname $(realpath $0))
fi
if [ -z "$PROJECT_SSH_PORT" ]; then
	PROJECT_SSH_PORT=9000
fi
