# Copyright (c) 2022 Alexander Williams <alexwilliams@protonmail.ch>
# SPDX-License-Identifier: LicenseRef-MIT-Alex

FROM dockerfile-dependencies AS dockerfile-base-after

# execute more tasks here
# RUN chown -R ubuntu:ubuntu /home/ubuntu/.ccache
# RUN chown -R ubuntu:ubuntu /home/ubuntu/.conda
