#!/bin/bash

# Copyright (c) 2022 Alexander Williams <alexwilliams@protonmail.ch>
# SPDX-License-Identifier: LicenseRef-MIT-Alex

cd /tmp/arrayfire/build && CTEST_OUTPUT_ON_FAILURE=1 make -j$(nproc) test
